import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { AppModule } from './app.module';
import { ValidationPipe } from '@nestjs/common';
import * as helmet from 'helmet';
import * as hbs from 'hbs';
import * as hbsUtils from 'hbs-utils';
import * as cookieParser from 'cookie-parser';
import * as csurf from 'csurf';
import * as compression from 'compression';
import * as hpp from 'hpp';
import { join } from 'path';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    cors: true,
    logger: ['error', 'warn', 'debug'],
  });
  app.useStaticAssets(join(__dirname, '..', '..', 'public'));
  app.setBaseViewsDir(join(__dirname, '..', '..', 'views'));
  hbs.registerPartials(join(__dirname, '..', '..', 'views/layout'));
  hbsUtils(hbs).registerWatchedPartials(
    join(__dirname, '..', '..', 'views/layout'),
  );
  app.setViewEngine('hbs');
  hbs.registerHelper('eq', function (a, b) {
    return a === b;
  });
  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
    }),
  );
  app.enableCors();
  app.use(cookieParser());
  app.use(
    helmet.contentSecurityPolicy({
      directives: {
        defaultSrc: ["'self'"],
        connectSrc: ["'self'", 'https://pagead2.googlesyndication.com'],
        scriptSrc: [
          "'self'",
          'https://pagead2.googlesyndication.com',
          'https://partner.googleadservices.com',
          'https://tpc.googlesyndication.com',
          'https://www.googletagservices.com',
          'https://adservice.google.com',
          'https://adservice.google.ad',
          'https://adservice.google.ae',
          'https://adservice.google.com.af',
          'https://adservice.google.com.ag',
          'https://adservice.google.com.ai',
          'https://adservice.google.al',
          'https://adservice.google.am',
          'https://adservice.google.co.ao',
          'https://adservice.google.com.ar',
          'https://adservice.google.as',
          'https://adservice.google.at',
          'https://adservice.google.com.au',
          'https://adservice.google.az',
          'https://adservice.google.ba',
          'https://adservice.google.com.bd',
          'https://adservice.google.be',
          'https://adservice.google.bg',
          'https://adservice.google.com.bh',
          'https://adservice.google.bi',
          'https://adservice.google.bj',
          'https://adservice.google.com.bn',
          'https://adservice.google.com.bo',
          'https://adservice.google.com.br',
          'https://adservice.google.bs',
          'https://adservice.google.bt',
          'https://adservice.google.co.bw',
          'https://adservice.google.by',
          'https://adservice.google.com.bz',
          'https://adservice.google.ca',
          'https://adservice.google.cd',
          'https://adservice.google.cf',
          'https://adservice.google.cg',
          'https://adservice.google.ch',
          'https://adservice.google.ci',
          'https://adservice.google.co.ck',
          'https://adservice.google.cl',
          'https://adservice.google.cm',
          'https://adservice.google.cn',
          'https://adservice.google.com.co',
          'https://adservice.google.co.cr',
          'https://adservice.google.com.cu',
          'https://adservice.google.cv',
          'https://adservice.google.com.cy',
          'https://adservice.google.cz',
          'https://adservice.google.de',
          'https://adservice.google.dj',
          'https://adservice.google.dk',
          'https://adservice.google.dm',
          'https://adservice.google.com.do',
          'https://adservice.google.dz',
          'https://adservice.google.com.ec',
          'https://adservice.google.ee',
          'https://adservice.google.com.eg',
          'https://adservice.google.es',
          'https://adservice.google.com.et',
          'https://adservice.google.fi',
          'https://adservice.google.com.fj',
          'https://adservice.google.fm',
          'https://adservice.google.fr',
          'https://adservice.google.ga',
          'https://adservice.google.ge',
          'https://adservice.google.gg',
          'https://adservice.google.com.gh',
          'https://adservice.google.com.gi',
          'https://adservice.google.gl',
          'https://adservice.google.gm',
          'https://adservice.google.gr',
          'https://adservice.google.com.gt',
          'https://adservice.google.gy',
          'https://adservice.google.com.hk',
          'https://adservice.google.hn',
          'https://adservice.google.hr',
          'https://adservice.google.ht',
          'https://adservice.google.hu',
          'https://adservice.google.co.id',
          'https://adservice.google.ie',
          'https://adservice.google.co.il',
          'https://adservice.google.im',
          'https://adservice.google.co.in',
          'https://adservice.google.iq',
          'https://adservice.google.is',
          'https://adservice.google.it',
          'https://adservice.google.je',
          'https://adservice.google.com.jm',
          'https://adservice.google.jo',
          'https://adservice.google.co.jp',
          'https://adservice.google.co.ke',
          'https://adservice.google.com.kh',
          'https://adservice.google.ki',
          'https://adservice.google.kg',
          'https://adservice.google.co.kr',
          'https://adservice.google.com.kw',
          'https://adservice.google.kz',
          'https://adservice.google.la',
          'https://adservice.google.com.lb',
          'https://adservice.google.li',
          'https://adservice.google.lk',
          'https://adservice.google.co.ls',
          'https://adservice.google.lt',
          'https://adservice.google.lu',
          'https://adservice.google.lv',
          'https://adservice.google.com.ly',
          'https://adservice.google.co.ma',
          'https://adservice.google.md',
          'https://adservice.google.me',
          'https://adservice.google.mg',
          'https://adservice.google.mk',
          'https://adservice.google.ml',
          'https://adservice.google.com.mm',
          'https://adservice.google.mn',
          'https://adservice.google.ms',
          'https://adservice.google.com.mt',
          'https://adservice.google.mu',
          'https://adservice.google.mv',
          'https://adservice.google.mw',
          'https://adservice.google.com.mx',
          'https://adservice.google.com.my',
          'https://adservice.google.co.mz',
          'https://adservice.google.com.na',
          'https://adservice.google.com.ng',
          'https://adservice.google.com.ni',
          'https://adservice.google.ne',
          'https://adservice.google.nl',
          'https://adservice.google.no',
          'https://adservice.google.com.np',
          'https://adservice.google.nr',
          'https://adservice.google.nu',
          'https://adservice.google.co.nz',
          'https://adservice.google.com.om',
          'https://adservice.google.com.pa',
          'https://adservice.google.com.pe',
          'https://adservice.google.com.pg',
          'https://adservice.google.com.ph',
          'https://adservice.google.com.pk',
          'https://adservice.google.pl',
          'https://adservice.google.pn',
          'https://adservice.google.com.pr',
          'https://adservice.google.ps',
          'https://adservice.google.pt',
          'https://adservice.google.com.py',
          'https://adservice.google.com.qa',
          'https://adservice.google.ro',
          'https://adservice.google.ru',
          'https://adservice.google.rw',
          'https://adservice.google.com.sa',
          'https://adservice.google.com.sb',
          'https://adservice.google.sc',
          'https://adservice.google.se',
          'https://adservice.google.com.sg',
          'https://adservice.google.sh',
          'https://adservice.google.si',
          'https://adservice.google.sk',
          'https://adservice.google.com.sl',
          'https://adservice.google.sn',
          'https://adservice.google.so',
          'https://adservice.google.sm',
          'https://adservice.google.sr',
          'https://adservice.google.st',
          'https://adservice.google.com.sv',
          'https://adservice.google.td',
          'https://adservice.google.tg',
          'https://adservice.google.co.th',
          'https://adservice.google.com.tj',
          'https://adservice.google.tl',
          'https://adservice.google.tm',
          'https://adservice.google.tn',
          'https://adservice.google.to',
          'https://adservice.google.com.tr',
          'https://adservice.google.tt',
          'https://adservice.google.com.tw',
          'https://adservice.google.co.tz',
          'https://adservice.google.com.ua',
          'https://adservice.google.co.ug',
          'https://adservice.google.co.uk',
          'https://adservice.google.com.uy',
          'https://adservice.google.co.uz',
          'https://adservice.google.com.vc',
          'https://adservice.google.co.ve',
          'https://adservice.google.vg',
          'https://adservice.google.co.vi',
          'https://adservice.google.com.vn',
          'https://adservice.google.vu',
          'https://adservice.google.ws',
          'https://adservice.google.rs',
          'https://adservice.google.co.za',
          'https://adservice.google.co.zm',
          'https://adservice.google.co.zw',
          'https://adservice.google.cat',
        ],
        imgSrc: [
          "'self'",
          'https://yt3.ggpht.com',
          'https://i.ytimg.com',
          'https://github.githubassets.com',
          'https://cdn.buymeacoffee.com',
          'https://pagead2.googlesyndication.com',
        ],
        mediaSrc: ["'self'", 'https://www.youtube.com'],
        frameSrc: [
          "'self'",
          'https://www.google.com',
          'https://tpc.googlesyndication.com',
          'https://googleads.g.doubleclick.net',
        ],
      },
    }),
    helmet.referrerPolicy({
      policy: 'same-origin',
    }),
    helmet.frameguard({
      action: 'sameorigin',
    }),
  );
  app.use(csurf({ cookie: true }));
  app.use(hpp());
  app.use(compression());
  await app.listen(process.env.PORT);
}
bootstrap();
